server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
         

      routes:
        - id: user-service-registro
          uri: lb://user-service
          predicates:
            - Path=/registro
          filters:
            - RewritePath=/registro, /api/usuarios/registro
            
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

